---
title: "Introduction to R for Bench Biologists"
author:
- "Nolan Ung"
- "nolan.ung@cammlab.org"
date: "8/2/2019"
output:
  html_document:
    toc: true 
    toc_depth: 2  
    number_sections: False  
    theme: united  
    highlight: tango  
---

# Workshop description 
 This 6 hr six week course is a brief introduction to the R statistical computing language designed specifically with bench biologists with no coding experience in mind so that they can get more done in less time and with less pain. This course is intended to be very hands-on and will include a final project of each individuals choosing, demonstrating the skills they have learned. There will be a brief introduction to programming principals, R and R studio, version control to make sure the students have the tools to use R effectively. We will cover importing data and common manipulations of data and data processing. The end of the course will cover data visualization both theory and practice. 
 
# learning objectives

- Understand the rational for using R and a scripting language over a GUI based workflow. 
- Become familiar with the various capabilities of the Rstudio IDE. 
- Understand how version control works and be able to use Rstudios git interface. 
- Basics of programming: assignment, data types, functions, arguments, help 
- How to install and load packages.
- Grasp how to import and combine data sets. 
- Basic data manipulation using `tidyr` and `dplyr` including pipes, mutate, group_by and summarize. 
- How to export data
- Explain the gestalt principals of data visualization and the goals of  data viz. 
- Be able to build simple plots using `ggplot2` and a simple heat map using `pheatmap`. 
- Build plots interactively and customize aesthetics and labels, facet plots and save figures. 
- Have the ability to take a simple experimental analysis from beginning to end. 
- Advance to the intermediate R course. 


# Office Hours 

I will holding Office hours in an effort to make sure that I am available for all questions and practice. I am still always available on Slack or and outside of office hours. 

<center> **Office Hours:  Fridays from 2pm-3pm location TBD**  </center>
 
 
# Prepartion for workshop

Please have the following installed on your laptop computer:  

* [R version 3.6.1 (Action of the Toes)](https://cran.r-project.org/) 
* [Rstudio version 1.2.1335](https://www.rstudio.com/products/rstudio/download/#download)
* [git](https://git-scm.com/downloads)
* [jupyter notebook for Mac](http://www.storybench.org/install-r-jupyter-notebook/) 
* [jupyter notebook for Windows](https://docs.anaconda.com/anaconda/navigator/tutorials/r-lang/)
  * [Anaconda](https://www.anaconda.com/distribution/)  
  
**Also please create a [GitHub](https://github.com/) account so that you can access the materials that we will use for the workshop. if you need help on how to create an account [have a look here.](https://www.wikihow.com/Create-an-Account-on-GitHub)**


downloaded these on your mac or windows lap top and bring it to the workshop. If you do not have a laptop please contact Nolan and/or Tom ahead of time and they can get you a loaner lap top. If you need assistance with downloading these two tools please feel free to contact Nolan for assistance. 


For detailed instructions check out htis video: 

<center>
<video width="620" height="540" controls>
  <source src="img/aat7744s4.mp4" type="video/mp4">
</video>
</center>

# Workshop Calendar  
Each session will last between 1 and 1.5 hrs. 
<br/>  
<br/>  


Date | Week # | Topic |  
-----|--------|-------| 
September 2nd | Week 1| [Before we start: Getting to know R, Rstudio and Git](00-before_we_start_IRBS.html)| 
September 9th| Week 2| Introduction to programming and R basics| 
September 16th | Week 3| Starting with data: importing and formatting|
September 23rd | Week 4| Manipulating data: wrangling and transforming data |
September 30th | Week 5| Data visualization: basic plots and heat maps|
October 7th | Week 6| Beginning to end real world examples|
  








 
 
 